 SET @start_d:='20141001';
SET @end_d:='20150930';

SELECT distcode,pe.check_hosp HOSPCODE,pe.CID ,pe.name,pe.lname,pe.birth,if(t01.CID is not null,"ชั่งแล้ว","ไม่ได้ชั่ง") act,t01.m
FROM (
SELECT SQL_BIG_RESULT 
			p.*,age(DATE_FORMAT(CONCAT(@b_year,'0701'),'%Y%m%d'),birth,'y') as age_y
		FROM
			t_person_db p
		WHERE LENGTH(TRIM(p.cid))=13 AND p.TYPEAREA in('1','3')
		ORDER BY  p.D_UPDATE DESC ,p.TYPEAREA ASC

) pe LEFT JOIN
(
SELECT p.cid,p.name,p.lname,DATE_FORMAT(n.DATE_SERV,'%m') m
FROM (select pn.cid,nt.* from nutrition nt left join person pn on nt.HOSPCODE=pn.HOSPCODE and nt.pid=pn.pid) n
INNER JOIN t_person_cid p ON n.CID=p.CID
INNER JOIN ( SELECT cid,max(DATE_SERV) DATE_SERV
FROM (select * from nutrition) tmp_nutrition
WHERE DATE_SERV BETWEEN @start_d AND @end_d
GROUP BY HOSPCODE,PID
) n1 ON n.cid=n1.cid AND n.DATE_SERV=n1.DATE_SERV
WHERE n.DATE_SERV BETWEEN @start_d AND @end_d AND TIMESTAMPDIFF(YEAR,p.BIRTH,n.DATE_SERV) BETWEEN 6 AND 14
GROUP BY n.CID
)t01 ON pe.CID=t01.cid
left join chospital h on pe.check_hosp=h.hoscode
WHERE pe.check_typearea in(1,3) AND pe.DISCHARGE in(9) AND
(TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 1 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 2 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 3 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 4 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 5 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 6 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 7 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 8 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 9 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 10 MONTH) BETWEEN 6 AND 14 OR
TIMESTAMPDIFF(YEAR,pe.BIRTH,@start_d+ INTERVAL 11 MONTH) BETWEEN 6 AND 14 )

GROUP BY pe.check_hosp,pe.CID,t01.m
