
 SET @start_d:='20141001';
SET @end_d:='20150930';

SELECT t01.HOSPCODE,t01.PID,t01.cid,t01.name,t01.lname,t01.birth,t01.m,if(t01.w_rs in('4','5') ,1,0) a
FROM (

SELECT n.HOSPCODE,n.PID,p.cid,p.name,p.lname,p.birth,n.DATE_SERV ,TIMESTAMPDIFF(MONTH,p.BIRTH,n.DATE_SERV) agem,p.SEX,n.HEIGHT,n.WEIGHT,DATE_FORMAT(n.DATE_SERV,'%m') m
,nutri_cal(TIMESTAMPDIFF(MONTH,p.BIRTH,max(n.DATE_SERV)),p.SEX,1,n.HEIGHT,n.WEIGHT) w_rs
FROM nutrition n INNER JOIN person p ON n.HOSPCODE=p.HOSPCODE AND n.PID=p.PID
INNER JOIN
( SELECT HOSPCODE,PID,max(DATE_SERV) DATE_SERV
FROM nutrition
WHERE DATE_SERV BETWEEN @start_d AND @end_d
GROUP BY HOSPCODE,PID
) n1 ON n.HOSPCODE=n1.HOSPCODE AND n.PID=n1.PID AND n.DATE_SERV=n1.DATE_SERV
WHERE n.DATE_SERV BETWEEN @start_d AND @end_d AND TIMESTAMPDIFF(YEAR,p.BIRTH,n.DATE_SERV) BETWEEN 5 AND 14
GROUP BY n.HOSPCODE,n.PID
ORDER BY HOSPCODE,PID

)t01
GROUP BY t01.HOSPCODE,t01.PID,t01.m